### ISSUE TITLE
Error: Failed during font subsetting

### ISSUE THREAD

**Issue by isAlmogK** [Munter/netlify-plugin-subfont#110]
Getting the following error on build 

`Plugin "netlify-plugin-subfont" failed

Error: Failed during font subsetting

LOG:
verions: {
"netlify-build": "16.1.1",
"netlify-plugin-subfont": "5.0.6",
"subfont": "5.4.1",
"assetgraph": "6.6.0"
}

Plugin configuration: {
"entryPoints": [
"*.html"
],
"recursive": true,
"inlineFonts": false,
"inlineCss": false,
"fontDisplay": "swap",
"fallbacks": true
}

Resolved entry points: [
"/opt/build/repo/packages/landing-gatsby/public/404.html",
"/opt/build/repo/packages/landing-gatsby/public/index.html"
]

Subfont called with: {
"recursive": true,
"inlineFonts": false,
"inlineCss": false,
"fontDisplay": "swap",
"fallbacks": true,
"inputFiles": [
"/opt/build/repo/packages/landing-gatsby/public/404.html",
"/opt/build/repo/packages/landing-gatsby/public/index.html"
],
"root": "packages/landing-gatsby/public",
"canonicalRoot": "https://almog.io",
"inPlace": true
}

Multiple @font-face with the same font-family/font-style/font-weight (maybe with different unicode-range?) is not supported yet: Raleway/normal/400

In "onPostBuild" event in "netlify-plugin-subfont" from Netlify app
at subsetFonts (/.netlify/plugins/node_modules/subfont/lib/subsetFonts.js:803:19)
at async subfont (/.netlify/plugins/node_modules/subfont/lib/subfont.js:230:24)
at async onPostBuild (/.netlify/plugins/node_modules/netlify-plugin-subfont/lib/index.js:69:5)`

**Comment by philwolstenholme** [comment]
I get a similar name of error, but this looks like the cause:

```
UnexpectedValue: auto (name)
In "onPostBuild" event in "netlify-plugin-subfont" from netlify.toml and package.json
```
