### ISSUE TITLE
Adding subfont plugin to netlify causes build to fail

### ISSUE THREAD

**Issue by tettoffensive** [Munter/netlify-plugin-subfont#26]
Hi, I was really inspired by the talk at Fronteers and decided to give this a try. I added a 
netlify.toml
```toml
[[plugins]]
package = "netlify-plugin-subfont"
```
and requirements.txt
```
fonttools
brotli
zopfli
```

And my build started failing on netlify.

The errors I'm getting are reporting an issue with a webpack loader which uses the "sharp" module. I don't know why these would be affected. They are for images.

```log
8:36:58 PM: ERROR in ./assets/mobile.png?sizes=205w+265w+388w+545w
8:36:58 PM: Module build failed (from ./node_modules/srcset-loader/index.js):
8:36:58 PM: Error:
8:36:58 PM: Something went wrong installing the "sharp" module
8:36:58 PM: Module did not self-register.
```

I did notice this line earlier in the log which I thought was strange:
```log
8:33:19 PM: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

As soon as I removed the 2 files, everything started building again.

I've attached my log:
[netlify-build-error-subfont.log](https://github.com/Munter/netlify-plugin-subfont/files/4507589/netlify-build-error-subfont.log)

**Comment by Munter** [comment]
This is a surprising behavior.

I doubt it has anything to do with subfont itself, since the build never gets to the plugin.

To me it looks like sharp just didn't install correctly. Why it works when you remove the plugin again I don't know. Maybe netlify has a caching layer that it flips back to when the hash of your config returns to the same value as before, and then the previous working install kicks in.

I think this one is out of my hands. But it might make sense to get @davidwells or @ehmicky to have a look at those logs

**Comment by ehmicky** [comment]
Hi @tettoffensive,

This does look like this is unrelated to `netlify-plugin-subfont`. We have a related issue [here](https://github.com/netlify/zip-it-and-ship-it/issues/79) about problems for people using Sharp, I think this might be the same issue.

Just to confirm: could you try removing `netlify-plugin-subfont` and see if it still fails? 

Also, would it be possible to share the deploy URL? They include few additional information on top of the logs that you posted (thanks for this).

**Comment by tettoffensive** [comment]
Yes, I removed the plugin and everything deployed successfully as before.

The failed deploy:
https://app.netlify.com/sites/tusk/deploys/5e9e69712bd9de191a6b77eb
The deploy url:
https://deploy-preview-40--tusk.netlify.app/

**Comment by ehmicky** [comment]
I have updated the issue about Sharp [in this comment](https://github.com/netlify/zip-it-and-ship-it/issues/79#issuecomment-620064809). It looks like the core problem is about using native modules inside Netlify Functions, which is a problem even without Build plugins enabled.

**Comment by tettoffensive** [comment]
So the reason it works for me when I don't have any plugins, is because I'm not using any Netlify functions? Am I understanding that correctly?

**Comment by ehmicky** [comment]
Is the build that passes not using Netlify Functions, and the one that does pass using them?

**Comment by tettoffensive** [comment]
Yes, and the sharp module is part of my Nuxt.js static website. I do have some functions but they don't use this module.

**Comment by ehmicky** [comment]
Thanks for the additional information: what do you get when you run `npm ls sharp`?

**Comment by tettoffensive** [comment]
```json
└─┬ srcset-loader@2.3.0 invalid
  └── sharp@0.24.1  extraneous
```

Guessing the `invalid` is because I'm installing from a [fork of srcset-loader](https://github.com/tettoffensive/srcset-loader.git#sharp-2.4).

**Comment by ehmicky** [comment]
It looks like your issue might not be related to `netlify-plugin-subfont`. This plugin does not use `sharp` (@Munter Please confirm if I'm mistaken). Based on this, should this this issue be transferred to the Netlify Build repository?

**Comment by tettoffensive** [comment]
That is correct. No plugin or netlify function I'm using involves `sharp`.
My static Nuxt.js website uses it and builds fine until I start using
plugins (presumably, `netlify-plugin-subfont` is the only plugin I've tried.

**Comment by Munter** [comment]
netlify-plugin-subfont does indeed not use sharp

**Comment by ehmicky** [comment]
I have opened https://github.com/netlify/zip-it-and-ship-it/issues/102 to track your problem @tettoffensive and I might need some additional debug information from you if this is possible :)

@munter This issue should be closed since this is not related to `netlify-plugin-subfont`.

**Comment by Munter** [comment]
@ehmicky Thank you for looking into this

**Comment by smth** [comment]
There does now seem to be an issue with adding that `requirements.txt` file. After [updating the build image](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239) I'm finding the build falls over when trying to install zopfli. Build succeeds if I remove the `requirements.txt` file (~I can't remember why / if that requirements file is necessary~ which is not required from v6 of this plugin).
