### ISSUE TITLE
Fallbacks option

### ISSUE THREAD

**Issue by toshimo** [Munter/netlify-plugin-subfont#37]
I'm using both subfont CLI (https://github.com/Munter/subfont) locally, and this netlify plugin on deploy. Thank you for your great work.
I noticed the `--no-fallbacks` option is not available here in this plugin unlike CLI. The option would be a great help for users of multibyte fonts, which often tend to be MB size. Could it be possible to make it accept `fallbacks` input in `netlify.toml`?

**Comment by Munter** [comment]
That sounds like a good idea

**Comment by Munter** [comment]
Released in v4.1.0
