### ISSUE TITLE
SyntaxError on deployed page

### ISSUE THREAD

**Issue by mhatvan** [Munter/netlify-plugin-subfont#54]
When I go to my deployed page on: https://dawcomparison.com, it throws: 
`Uncaught SyntaxError: Invalid or unexpected token` on Chrome and 
`SyntaxError: invalid escape sequence` on Firefox, but nothing breaks.

The error points me to no specific point in the minified bundle unfortunately.

You have to hard reload and empty cache to see the error popping up.

I am pretty sure that the optimizations work, Google Fonts loads nice and fast, thank you, but would be great to get rid of the error!

Could there be a conflict with `gatsby-plugin-google-fonts`?

**Comment by Munter** [comment]
There's some post-processing you have enabled to run after subfont, which makes a change to the subfont output.

It looks like the `onload` attribute in this async loaded CSS is causing it:

```html
<link rel='stylesheet' media='print' onload='this.media=\' all\'' href='https://d33wubrfki0l68.cloudfront.net/css/975e355ed01eed6ffab5a9847a5ead3b007e0c87/subfont/fonts-733500c979.css'/>
```

Subfont is not adding the async css changes. It adds this:

```html
<link rel="stylesheet" href="/subfont/fonts-733500c979.css">
```

Did you enabled Netlify's post processing optimizations?

**Comment by mhatvan** [comment]
Quick find!

These are the plugins that I have enabled currently, I am still experimenting with them:
![Screenshot from 2020-06-18 19-18-52](https://user-images.githubusercontent.com/16797721/85052104-ad5e3880-b198-11ea-981c-46677ed66cc8.png)

**Comment by Munter** [comment]
This seems to be the bug report to netlify that corresponds to this issue: https://github.com/netlify/build/issues/1384
