### ISSUE TITLE
Double font flicker when loading pages

### ISSUE THREAD

**Issue by daveredfern** [Munter/netlify-plugin-subfont#55]
Hello,

Thanks for creating this plugin. It’s super helpful for someone who is still learning about font subsets. I have it running on my website (https://daveredfern.com) and it seems to substantially reduce the time the custom font takes to load.

I’ve noticed a couple of things (that might be obvious to an expert) but I wasn’t sure about.

The first is in Chrome Dev Tools, the Network tab shows 3 versions of the font loading. Two subsets and the normal weight later. Is this expect?

![Screen Shot 2020-06-25 at 09 04 35](https://user-images.githubusercontent.com/183473/85682387-280ce380-b6c4-11ea-9ee3-291ae7948db9.jpg)

Also, I often notice a slight double flicker which I think is caused by the full font loading in slightly later. It can be a little jarring. Is this normal? Is there a way to stop the normal, full sized font loading in if the font subsets are working?

I tried to record a video but the flicker is a bit too quick to capture but if you visit my website (probably with caching disabled), you should see it.

Thanks in advance.

Dave.

**Comment by daveredfern** [comment]
Hi Peter (@Munter).

Thanks for the quick reply. That all makes sense.

> Does your netlify asset optimisation have any of these configurations enabled?

I’ve disabled the asset optimization (as far as I’m aware, there was no reason I had it enabled) and it’s removed the double subset fonts issue now.

> These are downloads of the font subsets from subfont, but these are downloaded from cloudfront instead of from your origin. This happens because of a bug in Netlify's asset optimisation. When NEtlify runs its asset optimisation it also seems to move assets to a cloudfront URL. But from what I can see it fails to recognise that there are preloads pointing to those assets and also update those url's. The result is a double download, and in your case it re-introduces the critical request chain of normal font loading, because these requests won't even start before the page has rendered.
> 
> @DavidWells Could you flag this internally at netlify? You really need to improve that asset optimisation script

Although I’ve fixed the issue by disabling asset optimization, I discovered if you use an absolute path, Netlify will ignore the asset. For example, using `https://daveredfern.com/style.css` won’t change to CloudFront but `/style.css` will.

> So these fonts might be loaded because of javascript injecting content on your page at runtime. OR, they might be caused by you applying the fonts to some characters that do not exist as a font glyph in the original font.

I think you’re correct. It looks like some glyphs are marked as not available but inside of the font file they actually are. Here’s an example of using a non-breaking hyphen. On the left if with the fallback disabled and on the right is with it enabled. It looks like the hyphen changed by the font indicating that the glyph does exist (although I maybe incorrect).

![Screen Shot 2020-06-25 at 11 17 43](https://user-images.githubusercontent.com/183473/85702066-f13fc900-b6d5-11ea-9fd3-7d4f2b6323c6.jpg)

I’ve attached two log files. This one is for before I made any changes (my original post):
[before-log.txt](https://github.com/Munter/netlify-plugin-subfont/files/4830579/before-log.txt)

And this one is for after I made the tweaks based on your suggestions and ideas: 
[after-log.txt](https://github.com/Munter/netlify-plugin-subfont/files/4830585/after-log.txt)

Cheers!

Dave.

**Comment by Munter** [comment]
> It looks like some glyphs are marked as not available but inside of the font file they actually are. Here’s an example of using a non-breaking hyphen. On the left if with the fallback disabled and on the right is with it enabled. It looks like the hyphen changed by the font indicating that the glyph does exist (although I maybe incorrect).

@papandreou This might be a bug in subfont

**Comment by papandreou** [comment]
From the logs and the discussion on the source-serif-pro issue it seems like it's fully explained by that hyphen and the emojis missing from the original font.

The attached logs do warn about it:

```
8:52:52 AM:  ⚠ WARN: Missing glyph fallback detected.
8:52:52 AM:          When your primary webfont doesn't contain the glyphs you use, your browser will load your fallback fonts, which will be a potential waste of bandwidth.         These glyphs are used on your site, but they don't exist in the font you applied to them:         - \u{2011} (‑) in font-family 'Source Serif Pro' (normal/normal) at _site/404.html:1:11889
```

It's a case that's currently not handled well by subfont's strategy of adding the subset font-family as the highest prioritized one. When we realized that, we added that warning, but we could invest some time in trying to actually fix it.

When @Munter and I last discussed it, I believe the best idea that came up was to inject an `unicode-range` property into the original `@font-face` declaration. That would make the browser know up front that the original font doesn't contain those characters either, and that it should get them from the fallback font. Implementing that shouldn't really be that difficult as we're already doing all the work in order to display that warning. I think the main downside is that `unicode-range` properties can be wordy and will add some weight to the page.

@daveredfern, until we look into that, could you try manually adding `unicode-range` to the `@font-face` declarations of `Source Serif Pro`?

**Comment by Munter** [comment]
@papandreou The thing I'm confused about is that the hyphen _does_ actually change when the original fonts have been loaded, despite that unicode codepoint obviously not being mapped to a glyph in the font. Is there some browser glyph snapping we are not aware of, where the browser or OS choses to render a different glyph that is known to look similar?

**Comment by papandreou** [comment]
@Munter, isn’t that because the browser falls back to `serif` once it learns that the original `Source Serif Pro` doesn’t contain the hyphen?

**Comment by daveredfern** [comment]
@papandreou I don’t think that’s the case. The following screenshot shows on the left the subfont (with no fallback) and on the right the subfont with the full font fallback. If it was defaulting back to serif, they would be the same but they’re not?

![85702066-f13fc900-b6d5-11ea-9fd3-7d4f2b6323c6](https://user-images.githubusercontent.com/183473/85919172-ed8c7d80-b860-11ea-8ea4-61d0d4184c7b.jpg)

**Comment by papandreou** [comment]
Hmm, yeah, that does sound likely. Still seems like there's a good chance that injecting `unicode-range` will prevent the downloading of the original font, though.

**Comment by papandreou** [comment]
It does seem to do the trick: https://github.com/Munter/subfont/pull/100 :sunglasses:
