### ISSUE TITLE
'Local subsetting is not possible because fonttools are not installed' - but `fonttools` is listed in `requirements.txt`

### ISSUE THREAD

**Issue by philwolstenholme** [Munter/netlify-plugin-subfont#84]
Hi,

I installed the plugin via the Netlify web UI and it worked really well for a few weeks but I've recently started getting this message: 

> Local subsetting is not possible because fonttools are not installed. Falling back to only subsetting Google Fonts. Run `pip install fonttools brotli zopfli` to enable local font subsetting

This is off, as my `requirements.txt` file in my project root contains `fonttools`:

```
fonttools
brotli
zopfli
```

I can't think of what may have changed to stop the plugin from working… I don't suppose you have any ideas?

Here is the log output:

```
12:23:51 AM: ────────────────────────────────────────────────────────────────
12:23:51 AM:   3. onPostBuild command from netlify-plugin-subfont            
12:23:51 AM: ────────────────────────────────────────────────────────────────
12:23:51 AM: ​
12:23:51 AM: Running subfont version 5.2.5
12:23:51 AM:  ✔ 0.001 secs: logEvents
12:23:55 AM:  ✔ 4.217 secs: loadAssets
12:23:56 AM:  ⚠ WARN: ENOENT: no such file or directory, open 'dist/index.no-css'
12:23:56 AM:  ⚠ WARN: ENOENT: no such file or directory, open 'dist/index.no-js'
12:23:57 AM:  ✔ 1.608 secs: populate
12:23:58 AM:  ✔ 0.579 secs: checkIncompatibleTypes
12:23:58 AM:  ✔ 0.341 secs: applySourceMaps
12:23:58 AM:  ✔ 0.037 secs: populate
12:24:42 AM:  ℹ INFO: Local subsetting is not possible because fonttools are not installed. Falling back to only subsetting Google Fonts. Run `pip install fonttools brotli zopfli` to enable local font subsetting
12:24:42 AM:  ℹ INFO: Unoptimised fonts:
12:24:42 AM:           - dist/assets/fonts/roboto-slab-v12-latin-700.woff2
12:24:42 AM:           - dist/assets/fonts/roboto-slab-v12-latin-regular.woff2
12:24:42 AM:           - dist/assets/fonts/roboto-slab-v12-latin-700.woff2
12:24:42 AM:           - dist/assets/fonts/roboto-slab-v12-latin-regular.woff2
12:24:43 AM:  ✔ 0.369 secs: compressJavaScript
12:24:43 AM:  ✔ 0.034 secs: writeAssetsToDisc
12:24:43 AM: HTML/JS/CSS size increase: 2.98 kB
12:24:43 AM: Total savings: -2.98 kB
12:24:43 AM: Output written to file:///opt/build/repo/dist/
```

**Comment by Munter** [comment]
The only idea I have is that https://github.com/netlify/build might have had a change that somehow affected the behavior. This plugin's code certainly hasn't changed in a long time, so I doubt it would be in this repository unless there has been a breaking change in the plugin interface that I'm not aware of.

@ehmicky Do you think a recent (~14 days ago) change to https://github.com/netlify/build might have inadvertently broken how python dependencies are installed or copied into the working container when running build plugins?

**Comment by Munter** [comment]
There is one way of working around this missing `fonttools` installation. Subfont has an experimental flag to enable local font subsetting using a wasm build of the harfbuzz font subsetter. This requires no OS-level installation, just standard npm install.

I would take a pull request that:
- Adds the equivalent of https://github.com/Munter/subfont/blob/master/lib/parseCommandLineOptions.js#L100-L105 to `manifest.yml`
- Validates that this error disappears when `fonttools` is not installed
- Documents the additional configuration option in the plugin README

**Comment by ehmicky** [comment]
`netlify/build` does not have any code related to Python in itself. However, it runs within a container that Netlify calls [the `build-image`](https://github.com/netlify/build-image) which is a Ubuntu Docker image which pre-installs some additional software. However, the most recent commit [related to Python there is from February 2020](https://github.com/netlify/build-image/pull/376), it does not look like the change is coming from our end, unless you have recently updated your build image version @philwolstenholme

**Comment by philwolstenholme** [comment]
So I did a bit more reading of my logs and noticed a deprecation warning coming from Pip. Netlify's [default Python version is 2.7](https://github.com/netlify/build-image/blob/xenial/included_software.md#user-content-languages:~:text=install.-,Python), but I believe that's EOL now.

Setting a `PYTHON_VERSION` environmental variable to `3.7` seems to have fixed the issue, so it wasn't anything to do with Subfont at all :)

@ghmicky, thanks for your time, and @Munter thank you very much for your work on Subfont!
